before_script:
    - pacman -Syy --noconfirm; pacman -Syu --noconfirm; pacman-db-upgrade; rm -rf /var/cache/pacman/pkg/*.tar.xz

build:
    script:
        - cd src/
        - ./autogen.sh
        - ./configure
        - make
