before_script:
    - pacman -Syy --noconfirm; pacman -Syu --noconfirm; pacman-db-upgrade; rm -rf /var/cache/pacman/pkg/*.tar.xz

build:
    script:
        - cd src/
        - ./autogen.sh
        - make
test:
    script:
        - cd test/
        - ./autogen.sh
        - make
        - ./test_kinesixd

